### ISSUE TITLE
More comprehensive

### ISSUE THREAD

**Issue by geekjourneyx** [RyanDaDeng/laravel-api-module-generator#1]
[Module Management](https://github.com/nWidart/laravel-modules) In Laravel. However.I forked a version that satisfies the [api generator](https://github.com/reallyli/laravel-modules)

**Comment by RyanDaDeng** [comment]
Hello reallyli, thank you for being the first issuer.  when I was about to start this project, I have already searched google and also found your mentioned project. I haven’t fully played with the package yet, I might give it a try tonight.

As titled in my description part, the package I’m working on is lightweight and I’m trying to make it as simple as possible. The core basis of this package is using my other project which is Laravel File Generator, this is actually the main part that generates any dynamic traits interfaces and classes you want without creating any stubs. 

Yeah, I might end up with the similar staff as the project you mentioned. I will get back to you after I play with that project.

**Comment by RyanDaDeng** [comment]
By the way, do you want me to implement new feature (api generator) based on the one you mentioned?

**Comment by RyanDaDeng** [comment]
Hello, I just have decided a decision to re-organise that code and also improve that package as well along with my features. This issue will be transfer to my new git repo.
